// Фрилаб — трекер клиентов. Данные хранятся в облаке (Supabase), доступ — по e-mail/паролю.

const SUPABASE_URL = 'https://wwljbdfbrbzfyceqgqhe.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3bGpiZGZicmJ6ZnljZXFncWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1MTc3MTgsImV4cCI6MjEwNjA5MzcxOH0.R_51onVZkX157qNvnz_fQuASK0Z7KGOywGHiqqWZN7A';

const sb = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

/** @typedef {{
 *   id:string, name:string, type:'recurring'|'oneoff', tasksDesc:string,
 *   planAmount:number|null, planDay:number|null, planDate:string|null,
 *   contract:{enabled:boolean, payerType:'individual'|'company'},
 *   createdAt:string
 * }} Client */
/** @typedef {{id:string, clientId:string, task:string, amount:number, planDate:string, factDate:string|null, createdAt:string}} Payment */

function normalizeClient(c) {
  return {
    id: c.id,
    name: c.name,
    type: c.type === 'oneoff' ? 'oneoff' : 'recurring',
    tasksDesc: c.tasksDesc ?? c.note ?? '',
    planAmount: c.planAmount != null ? Number(c.planAmount) : null,
    planDay: c.planDay != null ? Number(c.planDay) : null,
    planDate: c.planDate || null,
    planFrequency: c.planFrequency === 'weekly' ? 'weekly' : 'monthly',
    planWeekday: c.planWeekday != null ? Number(c.planWeekday) : null,
    planAmount2: c.planAmount2 != null ? Number(c.planAmount2) : null,
    planDay2: c.planDay2 != null ? Number(c.planDay2) : null,
    contract: c.contract && typeof c.contract === 'object'
      ? { enabled: !!c.contract.enabled, payerType: c.contract.payerType === 'company' ? 'company' : 'individual' }
      : { enabled: false, payerType: 'individual' },
    isDemo: !!c.isDemo,
    createdAt: c.createdAt || todayISO(),
  };
}

// ---------- Supabase: соответствие строк БД и объектов приложения ----------

function rowToClient(row) {
  return normalizeClient({
    id: row.id,
    name: row.name,
    type: row.type,
    tasksDesc: row.tasks_desc,
    planAmount: row.plan_amount,
    planDay: row.plan_day,
    planDate: row.plan_date,
    planFrequency: row.plan_frequency,
    planWeekday: row.plan_weekday,
    planAmount2: row.plan_amount2,
    planDay2: row.plan_day2,
    contract: { enabled: row.contract_enabled, payerType: row.payer_type },
    isDemo: !!row.is_demo,
    createdAt: row.created_at,
  });
}

function clientToRow(c) {
  return {
    name: c.name,
    type: c.type,
    tasks_desc: c.tasksDesc || '',
    plan_amount: c.planAmount,
    plan_day: c.planDay,
    plan_date: c.planDate,
    plan_frequency: c.planFrequency || 'monthly',
    plan_weekday: c.planWeekday ?? null,
    plan_amount2: c.planAmount2 ?? null,
    plan_day2: c.planDay2 ?? null,
    contract_enabled: !!(c.contract && c.contract.enabled),
    payer_type: (c.contract && c.contract.payerType) || 'individual',
    is_demo: !!c.isDemo,
  };
}

function rowToPayment(row) {
  return {
    id: row.id,
    clientId: row.client_id,
    task: row.task,
    amount: Number(row.amount) || 0,
    planDate: row.plan_date,
    factDate: row.fact_date,
    autoGenerated: !!row.auto_generated,
    createdAt: row.created_at,
  };
}

function paymentToRow(p) {
  return {
    client_id: p.clientId,
    task: p.task,
    amount: p.amount,
    plan_date: p.planDate,
    fact_date: p.factDate,
    auto_generated: !!p.autoGenerated,
  };
}

let state = { clients: [], payments: [] };

async function fetchState() {
  const [{ data: clientRows, error: cErr }, { data: paymentRows, error: pErr }] = await Promise.all([
    sb.from('clients').select('*'),
    sb.from('payments').select('*'),
  ]);
  if (cErr || pErr) {
    console.error(cErr || pErr);
    showToast('Не удалось загрузить данные из облака');
    return;
  }
  state = {
    clients: (clientRows || []).map(rowToClient),
    payments: (paymentRows || []).map(rowToPayment),
  };
  await syncAllSchedules();
  setReportPreset('month');
  renderAll();
}

function uid() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

// ---------- Форматирование ----------

const moneyFmt = new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 });
function formatMoney(n) {
  return moneyFmt.format(Math.round(Number(n) || 0)) + ' ₽';
}

// ---------- Небольшие UI-эффекты (анимация цифр, конфетти) ----------

const prefersReducedMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

// Плавно "наматывает" число от 0 до целевого значения при появлении на экране
function animateNumber(el, to, duration = 700) {
  if (prefersReducedMotion) { el.textContent = formatMoney(to); return; }
  const start = performance.now();
  function tick(now) {
    const t = Math.min(1, (now - start) / duration);
    const eased = 1 - Math.pow(1 - t, 3);
    el.textContent = formatMoney(to * eased);
    if (t < 1) requestAnimationFrame(tick);
    else el.textContent = formatMoney(to);
  }
  requestAnimationFrame(tick);
}

function animateValuesIn(container) {
  container.querySelectorAll('[data-animate-value]').forEach(el => {
    animateNumber(el, Number(el.dataset.animateValue) || 0);
  });
}

// Небольшой всплеск конфетти в точке клика — обратная связь при отметке платежа оплаченным
function celebrateAt(x, y) {
  if (prefersReducedMotion) return;
  const colors = ['#6C3CE9', '#FF7A50', '#1FAB6B', '#F0A020'];
  const count = 10;
  for (let i = 0; i < count; i++) {
    const el = document.createElement('span');
    el.className = 'confetti-piece';
    el.style.background = colors[i % colors.length];
    el.style.left = x + 'px';
    el.style.top = y + 'px';
    const angle = (Math.PI * 2 * i) / count + Math.random() * 0.5;
    const dist = 36 + Math.random() * 28;
    el.style.setProperty('--dx', `${Math.cos(angle) * dist}px`);
    el.style.setProperty('--dy', `${Math.sin(angle) * dist}px`);
    document.body.appendChild(el);
    el.addEventListener('animationend', () => el.remove());
  }
}

// ---------- Тёмная тема ----------

function applyTheme(theme) {
  if (theme === 'dark') document.documentElement.setAttribute('data-theme', 'dark');
  else document.documentElement.removeAttribute('data-theme');
  const sun = document.getElementById('themeIconSun');
  const moon = document.getElementById('themeIconMoon');
  if (sun) sun.hidden = theme === 'dark';
  if (moon) moon.hidden = theme !== 'dark';
}

function initTheme() {
  let saved = null;
  try { saved = localStorage.getItem('freelab-theme'); } catch (e) {}
  applyTheme(saved === 'dark' ? 'dark' : 'light');
}

function toggleTheme() {
  const next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
  applyTheme(next);
  try { localStorage.setItem('freelab-theme', next); } catch (e) {}
}

document.getElementById('btnTheme').addEventListener('click', toggleTheme);
document.getElementById('btnThemeMobile')?.addEventListener('click', toggleTheme);

initTheme();

// ---------- Skeleton-заглушки на время первой загрузки данных ----------

function renderSkeleton() {
  const statsEl = document.getElementById('stats');
  if (statsEl) {
    statsEl.innerHTML = `
      <div class="tile tile--hero skeleton"><div class="tile__value">0 ₽</div></div>
      <div class="tile tile--small skeleton"><div class="tile__value">0 ₽</div></div>
      <div class="tile tile--small skeleton"><div class="tile__value">0 ₽</div></div>
      <div class="tile tile--wide skeleton"><div class="tile__value">0 ₽</div></div>
    `;
  }
  const calendarEl = document.getElementById('paymentsCalendar');
  if (calendarEl) {
    calendarEl.innerHTML = `<div class="skeleton" style="height:360px; border-radius:14px;"></div>`;
  }
}

function formatDateShort(iso) {
  if (!iso) return '—';
  const d = new Date(iso + 'T00:00:00');
  if (isNaN(d)) return '—';
  return d.toLocaleDateString('ru-RU', { day: 'numeric', month: 'short' });
}

function todayISO() {
  const d = new Date();
  return toISO(d);
}

function toISO(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

// ---------- Автоматический график ожидаемых платежей ----------

const SCHEDULE_HORIZON_MONTHS = 6;

function daysInMonth(year, monthIndex) {
  return new Date(year, monthIndex + 1, 0).getDate();
}

// Дата в конкретном месяце с "прилипанием" ко дню (напр. 31 число в феврале -> последний день месяца)
function dateForDayInMonth(year, monthIndex, day) {
  const clamped = Math.min(day, daysInMonth(year, monthIndex));
  return toISO(new Date(year, monthIndex, clamped));
}

// Ближайшая дата >= fromISO, приходящаяся на нужный день недели (1=понедельник...7=воскресенье)
function firstWeekdayOnOrAfter(fromISO, isoWeekday) {
  const d = new Date(fromISO + 'T00:00:00');
  const currentIsoWeekday = d.getDay() === 0 ? 7 : d.getDay();
  const diff = (isoWeekday - currentIsoWeekday + 7) % 7;
  d.setDate(d.getDate() + diff);
  return toISO(d);
}

function addDaysISO(iso, days) {
  const d = new Date(iso + 'T00:00:00');
  d.setDate(d.getDate() + days);
  return toISO(d);
}

function addMonthsHorizonISO(fromISO, months) {
  const d = new Date(fromISO + 'T00:00:00');
  d.setMonth(d.getMonth() + months);
  return toISO(d);
}

// Считает ожидаемые начисления для клиента между fromISO и toISO (включительно) по данным его карточки
function computeScheduledOccurrences(client, fromISO, toISO_) {
  if (client.type !== 'recurring' || !client.planAmount) return [];
  const out = [];

  if (client.planFrequency === 'weekly') {
    if (!client.planWeekday) return out;
    let date = firstWeekdayOnOrAfter(fromISO, client.planWeekday);
    while (date <= toISO_) {
      out.push({ planDate: date, amount: client.planAmount, task: 'Еженедельный платёж' });
      date = addDaysISO(date, 7);
    }
    return out;
  }

  // Ежемесячно
  if (client.planDay) {
    const start = new Date(fromISO + 'T00:00:00');
    const end = new Date(toISO_ + 'T00:00:00');
    let y = start.getFullYear(), m = start.getMonth();
    const task = client.planAmount2 ? 'Аванс' : 'Плановый платёж';
    while (y < end.getFullYear() || (y === end.getFullYear() && m <= end.getMonth())) {
      const date = dateForDayInMonth(y, m, client.planDay);
      if (date >= fromISO && date <= toISO_) out.push({ planDate: date, amount: client.planAmount, task });
      m++;
      if (m > 11) { m = 0; y++; }
    }
  }
  if (client.planAmount2 && client.planDay2) {
    const start = new Date(fromISO + 'T00:00:00');
    const end = new Date(toISO_ + 'T00:00:00');
    let y = start.getFullYear(), m = start.getMonth();
    while (y < end.getFullYear() || (y === end.getFullYear() && m <= end.getMonth())) {
      const date = dateForDayInMonth(y, m, client.planDay2);
      if (date >= fromISO && date <= toISO_) out.push({ planDate: date, amount: client.planAmount2, task: 'Остаток' });
      m++;
      if (m > 11) { m = 0; y++; }
    }
  }
  return out;
}

// Дополняет график клиента недостающими автосозданными платежами на горизонт вперёд,
// не трогая уже существующие (в т.ч. добавленные вручную) записи.
async function syncClientSchedule(client) {
  if (client.type !== 'recurring' || !client.planAmount) return;
  const from = todayISO();
  const to = addMonthsHorizonISO(from, SCHEDULE_HORIZON_MONTHS);
  const occurrences = computeScheduledOccurrences(client, from, to);
  if (!occurrences.length) return;

  const existingKeys = new Set(
    state.payments
      .filter(p => p.clientId === client.id && p.autoGenerated)
      .map(p => `${p.planDate}|${p.task}`)
  );
  const toInsert = occurrences.filter(o => !existingKeys.has(`${o.planDate}|${o.task}`));
  if (!toInsert.length) return;

  const rows = toInsert.map(o => paymentToRow({
    clientId: client.id, task: o.task, amount: o.amount, planDate: o.planDate, factDate: null, autoGenerated: true,
  }));
  // upsert + ignoreDuplicates: если та же запись (клиент/дата/тип) уже есть в базе
  // (например, из-за параллельной загрузки), она просто не будет продублирована
  const { data, error } = await sb.from('payments')
    .upsert(rows, { onConflict: 'client_id,plan_date,task,auto_generated', ignoreDuplicates: true })
    .select();
  if (error) { console.error(error); return; }
  state.payments.push(...(data || []).map(rowToPayment));
}

async function syncAllSchedules() {
  for (const client of state.clients) {
    await syncClientSchedule(client);
  }
}

// Удаляет ещё не наступившие и не оплаченные автосозданные платежи клиента
// (используется перед пересборкой графика после изменения условий в карточке)
async function clearFutureAutoPayments(clientId) {
  const from = todayISO();
  const { error } = await sb.from('payments')
    .delete()
    .eq('client_id', clientId)
    .eq('auto_generated', true)
    .is('fact_date', null)
    .gte('plan_date', from);
  if (error) { console.error(error); return; }
  state.payments = state.payments.filter(p =>
    !(p.clientId === clientId && p.autoGenerated && !p.factDate && p.planDate >= from)
  );
}

const WEEKDAYS = ['воскресенье','понедельник','вторник','среда','четверг','пятница','суббота'];
const WEEKDAY_SHORT = ['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const MONTHS = ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];

function todayLabel() {
  const d = new Date();
  return `${capitalize(WEEKDAYS[d.getDay()])}, ${d.getDate()} ${MONTHS[d.getMonth()]}`;
}
function capitalize(s) { return s.charAt(0).toUpperCase() + s.slice(1); }

// ---------- Производные данные: клиенты и налог ----------

function getClient(id) { return state.clients.find(c => c.id === id); }

function clientTaxRatePercent(client) {
  if (!client || !client.contract || !client.contract.enabled) return 0;
  return client.contract.payerType === 'company' ? 6 : 4;
}
function paymentTax(payment) {
  const c = getClient(payment.clientId);
  const rate = clientTaxRatePercent(c);
  return (Number(payment.amount) || 0) * rate / 100;
}
function paymentNet(payment) {
  return (Number(payment.amount) || 0) - paymentTax(payment);
}

// ---------- Производные данные: статусы и месяц ----------

function deriveStatus(payment) {
  if (payment.factDate) return 'paid';
  if (payment.planDate < todayISO()) return 'overdue';
  return 'pending';
}

function isInCurrentMonth(iso) {
  if (!iso) return false;
  const d = new Date(iso + 'T00:00:00');
  const now = new Date();
  return d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth();
}

function computeStats() {
  let expected = 0, received = 0, pending = 0, overdue = 0;
  for (const p of state.payments) {
    const status = deriveStatus(p);
    if (isInCurrentMonth(p.planDate)) expected += Number(p.amount) || 0;
    if (status === 'paid' && isInCurrentMonth(p.factDate)) received += Number(p.amount) || 0;
    if (status === 'pending' && isInCurrentMonth(p.planDate)) pending += Number(p.amount) || 0;
    if (status === 'overdue') overdue += Number(p.amount) || 0;
  }
  return { expected, received, pending, overdue };
}

function computeTaxForecast() {
  let gross = 0, tax = 0;
  for (const p of state.payments) {
    if (!isInCurrentMonth(p.planDate)) continue;
    const c = getClient(p.clientId);
    const rate = clientTaxRatePercent(c);
    if (!rate) continue;
    gross += Number(p.amount) || 0;
    tax += paymentTax(p);
  }
  return { gross, tax, net: gross - tax };
}

// ---------- Рендер: статистика ----------

function overallSparklineSVG() {
  const now = new Date();
  const keys = [];
  for (let i = 5; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    keys.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
  }
  const byKey = Object.fromEntries(keys.map(k => [k, 0]));
  state.payments.forEach(p => {
    if (!p.factDate) return;
    const key = monthGroupKey(p.factDate);
    if (key in byKey) byKey[key] += Number(p.amount) || 0;
  });
  const values = keys.map(k => byKey[k]);
  if (values.filter(v => v > 0).length < 2) return '';

  const w = 260, h = 46, pad = 3;
  const max = Math.max(...values, 1);
  const stepX = (w - pad * 2) / (values.length - 1);
  const points = values.map((v, i) => [
    pad + i * stepX,
    h - pad - (v / max) * (h - pad * 2),
  ]);
  const path = points.map((p, i) => (i === 0 ? 'M' : 'L') + p[0].toFixed(1) + ',' + p[1].toFixed(1)).join(' ');
  return `<path d="${path}" fill="none" stroke="#FF7A50" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`;
}

function renderStats() {
  const s = computeStats();
  const el = document.getElementById('stats');
  const spark = overallSparklineSVG();
  el.innerHTML = `
    <div class="tile tile--hero tile--dark">
      <div class="hero-blob"></div>
      <div class="tile__icon">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M12 2v20M17 5.5c0-1.9-2.2-3.5-5-3.5s-5 1.6-5 3.5 2.2 3 5 3 5 1.1 5 3-2.2 3.5-5 3.5-5-1.6-5-3.5" stroke="#1B1626" stroke-width="2.1" stroke-linecap="round"/></svg>
      </div>
      <div>
        <div class="tile__label">Ожидается в этом месяце</div>
        <div class="tile__value" data-animate-value="${s.expected}">0 ₽</div>
      </div>
      ${spark ? `<svg class="hero-spark" viewBox="0 0 260 46" preserveAspectRatio="none">${spark}</svg>` : ''}
    </div>
    <div class="tile tile--small">
      <div class="tile__icon">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M5 13l4 4L19 7" stroke="#1FAB6B" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
      </div>
      <div>
        <div class="tile__label" style="color:var(--muted)">Уже получено</div>
        <div class="tile__value" data-animate-value="${s.received}">0 ₽</div>
      </div>
    </div>
    <div class="tile tile--small is-pending">
      <div class="tile__icon">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="8.5" stroke="#B87700" stroke-width="2.1"/><path d="M12 7.5V12l3 2" stroke="#B87700" stroke-width="2.1" stroke-linecap="round"/></svg>
      </div>
      <div>
        <div class="tile__label" style="color:var(--muted)">В ожидании оплаты</div>
        <div class="tile__value" data-animate-value="${s.pending}">0 ₽</div>
      </div>
    </div>
    <div class="tile tile--wide">
      <div class="tile__icon">
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M12 8v5" stroke="#E8493C" stroke-width="2.3" stroke-linecap="round"/><circle cx="12" cy="16.3" r="1.1" fill="#E8493C"/><circle cx="12" cy="12" r="9" stroke="#E8493C" stroke-width="2.1"/></svg>
      </div>
      <div class="tile__text">
        <div class="tile__label" style="color:var(--muted)">Просрочено</div>
        <div class="tile__value" data-animate-value="${s.overdue}">0 ₽</div>
      </div>
    </div>
  `;
  animateValuesIn(el);
}

function renderTaxForecast() {
  const el = document.getElementById('taxForecast');
  const hasContractClients = state.clients.some(c => c.contract && c.contract.enabled);
  if (!hasContractClients) {
    el.innerHTML = `<div class="forecastBand--empty">
      <span>Отметьте клиента «по договору», чтобы видеть здесь прогноз дохода и налога НПД за месяц</span>
    </div>`;
    return;
  }
  const f = computeTaxForecast();
  el.innerHTML = `
    <div class="forecastBand">
      <div class="forecastBand__item">
        <div class="forecastBand__label">Доход по договору за ${MONTHS[new Date().getMonth()]}</div>
        <div class="forecastBand__value" data-animate-value="${f.gross}">0 ₽</div>
      </div>
      <div class="forecastBand__item">
        <div class="forecastBand__label">Налог НПД</div>
        <div class="forecastBand__value" style="color:#FF9E7A;" data-animate-value="${f.tax}">0 ₽</div>
      </div>
      <div class="forecastBand__item">
        <div class="forecastBand__label">На руки</div>
        <div class="forecastBand__value" style="color:#7CE0AE;" data-animate-value="${f.net}">0 ₽</div>
      </div>
    </div>
  `;
  animateValuesIn(el);
}

// ---------- Рендер: прогресс по месяцу ----------

function renderMonthProgress() {
  const el = document.getElementById('monthProgress');
  if (!el) return;
  const s = computeStats();
  const total = s.expected || 0;
  if (!total) { el.innerHTML = ''; return; }
  const pct = Math.max(0, Math.min(100, Math.round((s.received / total) * 100)));
  el.innerHTML = `
    <div class="progressCard">
      <div class="progressCard__row">
        <span class="progressCard__label">Собрано за ${MONTHS[new Date().getMonth()]}</span>
        <span class="progressCard__pct">${pct}%</span>
      </div>
      <div class="progressCard__track"><div class="progressCard__fill" style="width:0%" data-target-width="${pct}"></div></div>
      <div class="progressCard__sub">${formatMoney(s.received)} из ${formatMoney(total)} по плану на месяц</div>
    </div>
  `;
  const fill = el.querySelector('.progressCard__fill');
  if (fill) requestAnimationFrame(() => { fill.style.width = fill.dataset.targetWidth + '%'; });
}

// ---------- Рендер: календарь поступлений ----------

let calendarMonthOffset = 0; // 0 = текущий месяц, +1 = следующий, -1 = предыдущий

function calendarTargetDate() {
  const now = new Date();
  return new Date(now.getFullYear(), now.getMonth() + calendarMonthOffset, 1);
}

function dayStatus(dayPayments, today) {
  const allPaid = dayPayments.every(p => p.factDate);
  const anyOverdue = dayPayments.some(p => !p.factDate && p.planDate < today);
  return allPaid ? 'paid' : anyOverdue ? 'overdue' : 'pending';
}

function renderPaymentsCalendar() {
  const el = document.getElementById('paymentsCalendar');
  if (!el) return;
  const target = calendarTargetDate();
  const year = target.getFullYear(), month = target.getMonth();
  const totalDays = daysInMonth(year, month);
  const firstIsoWeekday = new Date(year, month, 1).getDay() || 7; // 1=пн...7=вс

  const byDay = {};
  state.payments.forEach(p => {
    const d = new Date(p.planDate + 'T00:00:00');
    if (d.getFullYear() === year && d.getMonth() === month) {
      (byDay[d.getDate()] ||= []).push(p);
    }
  });

  const today = todayISO();
  const cells = [];
  const agendaDays = [];
  for (let i = 1; i < firstIsoWeekday; i++) cells.push('<div class="calendarDay calendarDay--empty"></div>');
  for (let day = 1; day <= totalDays; day++) {
    const iso = dateForDayInMonth(year, month, day);
    const dayPayments = byDay[day] || [];
    let cls = 'calendarDay';
    let chips = '';
    if (dayPayments.length) {
      cls += ' calendarDay--has-events';
      const shown = dayPayments.slice(0, 2);
      chips = shown.map(p => {
        const client = getClient(p.clientId);
        const name = client ? client.name : p.task;
        return `<div class="chip chip--${deriveStatus(p)}">${escapeHTML(name)} · ${formatMoney(p.amount)}</div>`;
      }).join('');
      if (dayPayments.length > shown.length) {
        chips += `<div class="chip chip--more">+ещё ${dayPayments.length - shown.length}</div>`;
      }
    }
    if (iso === today) cls += ' calendarDay--today';
    cells.push(`<div class="${cls}" ${dayPayments.length ? `data-action="open-day" data-date="${iso}"` : ''}>
      <div class="calendarDay__num">${day}</div>
      ${chips}
    </div>`);

    // Лента для узкого экрана: только дни, в которые что-то ожидается
    if (dayPayments.length) {
      const weekday = WEEKDAY_SHORT[(new Date(year, month, day).getDay() + 6) % 7];
      const items = dayPayments.map(p => {
        const client = getClient(p.clientId);
        const name = client ? client.name : p.task;
        return `<div class="agendaItem">
          <span class="agendaDot agendaDot--${deriveStatus(p)}"></span>
          <span class="agendaItem__name">${escapeHTML(name)}</span>
          <span class="agendaItem__amount">${formatMoney(p.amount)}</span>
        </div>`;
      }).join('');
      agendaDays.push(`<div class="agendaDay ${iso === today ? 'agendaDay--today' : ''}" data-action="open-day" data-date="${iso}">
        <div class="agendaDay__date">
          <span class="agendaDay__num">${day}</span>
          <span class="agendaDay__wd">${weekday}</span>
        </div>
        <div class="agendaDay__body">${items}</div>
      </div>`);
    }
  }

  const isCurrentMonth = calendarMonthOffset === 0;
  el.innerHTML = `
    <div class="calendarHead">
      <span class="calendarTitle">${MONTHS_NOM[month]}${year !== new Date().getFullYear() ? ' ' + year : ''}</span>
      <div class="calendarNav">
        <button type="button" data-action="calendar-prev">‹</button>
        ${isCurrentMonth ? '' : '<button type="button" class="calendarNavToday" data-action="calendar-today">Сегодня</button>'}
        <button type="button" data-action="calendar-next">›</button>
      </div>
    </div>
    <div class="calendarLegend">
      <span><i class="legendDot legendDot--pending"></i>Ожидается</span>
      <span><i class="legendDot legendDot--paid"></i>Оплачено</span>
      <span><i class="legendDot legendDot--overdue"></i>Просрочено</span>
    </div>
    <div class="calendarWeekdays">${WEEKDAY_SHORT.map(w => `<span>${w}</span>`).join('')}</div>
    <div class="calendarGrid">${cells.join('')}</div>
    <div class="calendarAgenda">${
      agendaDays.length
        ? agendaDays.join('')
        : '<div class="agendaEmpty">В этом месяце поступлений нет</div>'
    }</div>
  `;
}

// ---------- Демонстрационный пример для нового пользователя ----------

function hasDemoData() {
  return state.clients.some(c => c.isDemo);
}

async function createDemoData() {
  const today = todayISO();
  const now = new Date();
  // «Ожидается» держим внутри текущего месяца, иначе показатели месяца выйдут пустыми
  const endOfMonth = dateForDayInMonth(now.getFullYear(), now.getMonth(), daysInMonth(now.getFullYear(), now.getMonth()));
  const startOfMonth = dateForDayInMonth(now.getFullYear(), now.getMonth(), 1);
  const soon = [addDaysISO(today, 5), endOfMonth].sort()[0];
  // «Получено» тоже оставляем в этом месяце — иначе плитка «Уже получено» будет пустой
  const paid = [addDaysISO(today, -6), startOfMonth].sort().reverse()[0];
  // «Просрочено» не привязываем к месяцу: этот показатель считается по всем датам
  const late = addDaysISO(today, -3);
  const dayOf = iso => new Date(iso + 'T00:00:00').getDate();

  const demoClients = [
    { name: 'Онлайн-школа', type: 'recurring', tasksDesc: 'Веду соцсети', planAmount: 15000,
      planDay: dayOf(soon), planFrequency: 'monthly', contract: { enabled: true, payerType: 'company' }, isDemo: true },
    { name: 'Кофейня у дома', type: 'recurring', tasksDesc: 'Тексты для рассылки', planAmount: 6000,
      planDay: dayOf(paid), planFrequency: 'monthly', contract: { enabled: false, payerType: 'individual' }, isDemo: true },
    { name: 'Андрей (сайт)', type: 'oneoff', tasksDesc: '', planAmount: null,
      planDay: null, planFrequency: 'monthly', contract: { enabled: false, payerType: 'individual' }, isDemo: true },
  ];

  const inserted = [];
  for (const c of demoClients) {
    const { data, error } = await sb.from('clients').insert(clientToRow(normalizeClient(c))).select().single();
    if (error) throw error;
    inserted.push(rowToClient(data));
  }

  // Три записи, чтобы сразу были видны все статусы: оплачено, ожидается, просрочено.
  // У плановых стоит признак автосоздания — тогда генератор графика не продублирует их.
  const demoPayments = [
    { client_id: inserted[0].id, task: 'Плановый платёж', amount: 15000, plan_date: soon, fact_date: null, auto_generated: true },
    { client_id: inserted[1].id, task: 'Плановый платёж', amount: 6000, plan_date: paid, fact_date: paid, auto_generated: true },
    { client_id: inserted[2].id, task: 'Лендинг под ключ', amount: 20000, plan_date: late, fact_date: null, auto_generated: false },
  ];
  const { error: pErr } = await sb.from('payments').insert(demoPayments);
  if (pErr) throw pErr;

  await fetchState();
}

async function removeDemoData() {
  // Платежи удалятся сами — у связи client_id стоит каскадное удаление
  const { error } = await sb.from('clients').delete().eq('is_demo', true);
  if (error) throw error;
  await fetchState();
}

// ---------- Первый экран: приложение ещё пустое ----------

function renderFirstRun() {
  const el = document.getElementById('firstRun');
  if (!el) return false;
  const isEmpty = state.clients.length === 0;
  el.hidden = !isEmpty;
  // Пока данных нет, нули и пустой календарь только мешают
  ['stats', 'monthProgress', 'taxForecast', 'paymentsCalendar'].forEach(id => {
    const block = document.getElementById(id);
    if (block) block.hidden = isEmpty;
  });
  return isEmpty;
}

function renderDemoBanner() {
  const el = document.getElementById('demoBanner');
  if (el) el.hidden = !hasDemoData();
}

function openDayDetail(iso) {
  const dayPayments = state.payments.filter(p => p.planDate === iso);
  if (!dayPayments.length) return;
  const d = new Date(iso + 'T00:00:00');
  document.getElementById('dayDetailTitle').textContent = `${d.getDate()} ${MONTHS[d.getMonth()]}`;
  document.getElementById('dayDetailPayments').innerHTML = dayPayments.map(p => paymentRowHTML(p)).join('');
  document.getElementById('dayDetailModal').classList.add('is-open');
}

// ---------- Рендер: мини-график истории платежей клиента (спарклайн) ----------

function clientSparklineSVG(client) {
  const now = new Date();
  const keys = [];
  for (let i = 5; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    keys.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
  }
  const byKey = Object.fromEntries(keys.map(k => [k, 0]));
  state.payments.forEach(p => {
    if (p.clientId !== client.id || !p.factDate) return;
    const key = monthGroupKey(p.factDate);
    if (key in byKey) byKey[key] += Number(p.amount) || 0;
  });
  const values = keys.map(k => byKey[k]);
  if (values.filter(v => v > 0).length < 2) return ''; // мало истории — график не показателен

  const w = 84, h = 26, pad = 3;
  const max = Math.max(...values, 1);
  const stepX = (w - pad * 2) / (values.length - 1);
  const points = values.map((v, i) => [
    pad + i * stepX,
    h - pad - (v / max) * (h - pad * 2),
  ]);
  const path = points.map((p, i) => (i === 0 ? 'M' : 'L') + p[0].toFixed(1) + ',' + p[1].toFixed(1)).join(' ');
  const last = points[points.length - 1];
  return `
    <svg class="sparkline" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
      <path d="${path}" fill="none" stroke="var(--violet)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
      <circle cx="${last[0].toFixed(1)}" cy="${last[1].toFixed(1)}" r="2.4" fill="var(--violet)"/>
    </svg>
  `;
}

// ---------- Рендер: списки платежей ----------

function initials(name) {
  return name.trim().split(/\s+/).slice(0, 2).map(w => w[0]).join('').toUpperCase();
}

const AVATAR_PALETTE = [
  { bg: '#EFE6FF', fg: '#6C3CE9' },
  { bg: '#FFE8DE', fg: '#FF7A50' },
  { bg: '#E4F8EE', fg: '#1FAB6B' },
  { bg: '#FFF3DC', fg: '#B87700' },
];
function avatarColor(id) {
  let hash = 0;
  for (let i = 0; i < id.length; i++) hash = (hash * 31 + id.charCodeAt(i)) >>> 0;
  return AVATAR_PALETTE[hash % AVATAR_PALETTE.length];
}

function statusPill(status) {
  if (status === 'paid') return '<span class="pill pill--paid">Оплачено</span>';
  if (status === 'overdue') return '<span class="pill pill--overdue">Просрочено</span>';
  return '<span class="pill pill--pending">Ожидается</span>';
}

function paymentRowHTML(payment, opts = {}) {
  const client = getClient(payment.clientId);
  if (!client) return '';
  const status = deriveStatus(payment);
  const color = avatarColor(client.id);
  const rate = clientTaxRatePercent(client);

  const leftHTML = opts.compact
    ? `<div>
        <div class="row__title">${escapeHTML(payment.task)}</div>
      </div>`
    : `<div class="row__avatar" style="background:${color.bg}; color:${color.fg};">${initials(client.name)}</div>
      <div>
        <div class="row__title">${escapeHTML(client.name)}</div>
        <div class="row__sub">${escapeHTML(payment.task)}</div>
      </div>
      ${client.type === 'recurring' ? `<span class="badge badge--violet">
        <svg width="11" height="11" viewBox="0 0 24 24" fill="none"><path d="M17 2.1l4 4-4 4M7 21.9l-4-4 4-4M21 6.1H8a4 4 0 0 0-4 4v2M3 17.9h13a4 4 0 0 0 4-4v-2" stroke="#6C3CE9" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>
        ${client.planFrequency === 'weekly' ? 'Еженедельно' : 'Ежемесячно'}</span>` : ''}`;

  return `
    <div class="row ${status === 'overdue' ? 'row--overdue' : ''}" data-payment-id="${payment.id}">
      <div class="row__left">${leftHTML}</div>
      <div class="row__right">
        <div class="row__dates">
          <div class="row__dates-label">План / Факт</div>
          <div class="row__dates-value" style="${status === 'overdue' ? 'color:#E8493C;' : ''}">${formatDateShort(payment.planDate)} / ${formatDateShort(payment.factDate)}</div>
        </div>
        <div class="row__amount">
          <div>${formatMoney(payment.amount)}</div>
          ${rate > 0 ? `<div class="row__amount-sub">на руки ${formatMoney(paymentNet(payment))}</div>` : ''}
        </div>
        ${statusPill(status)}
        <div class="row__actions">
          ${status !== 'paid' ? `<button class="iconbtn" title="Отметить оплаченным" data-action="mark-paid" data-id="${payment.id}">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M5 13l4 4L19 7" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </button>` : ''}
          <button class="iconbtn" title="Редактировать" data-action="edit-payment" data-id="${payment.id}">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M4 20l.8-3.6L16 5.2a1.6 1.6 0 0 1 2.3 0l.5.5a1.6 1.6 0 0 1 0 2.3L7.6 19.2 4 20Z" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>
          </button>
          <button class="iconbtn iconbtn--danger" title="Удалить" data-action="delete-payment" data-id="${payment.id}">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M5 7h14M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2m-9 0 1 13a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2l1-13" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>
          </button>
        </div>
      </div>
    </div>
  `;
}

function emptyStateHTML(title, sub, btnLabel, action) {
  return `
    <div class="empty">
      <div class="empty__title">${title}</div>
      <div class="empty__sub">${sub}</div>
      ${btnLabel ? `<button class="btn btn--dark" data-action="${action}">${btnLabel}</button>` : ''}
    </div>
  `;
}

const MONTHS_NOM = ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];

function monthGroupKey(iso) {
  const d = new Date(iso + 'T00:00:00');
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

function monthGroupLabel(iso) {
  const d = new Date(iso + 'T00:00:00');
  const label = MONTHS_NOM[d.getMonth()];
  return d.getFullYear() === new Date().getFullYear() ? label : `${label} ${d.getFullYear()}`;
}

function sortByRelevance(a, b) {
  // Сначала просроченные, потом ожидающие (по дате), потом оплаченные (по дате оплаты, недавние сверху)
  const rank = s => (s === 'overdue' ? 0 : s === 'pending' ? 1 : 2);
  const ra = rank(deriveStatus(a)), rb = rank(deriveStatus(b));
  if (ra !== rb) return ra - rb;
  if (ra === 2) return (b.factDate || '').localeCompare(a.factDate || '');
  return (a.planDate || '').localeCompare(b.planDate || '');
}

// ---------- Рендер: клиенты ----------

const WEEKDAY_NAMES = { 1: 'понедельникам', 2: 'вторникам', 3: 'средам', 4: 'четвергам', 5: 'пятницам', 6: 'субботам', 7: 'воскресеньям' };

function clientPlanLineText(client) {
  if (!client.planAmount) return '';
  if (client.type === 'recurring') {
    if (client.planFrequency === 'weekly') {
      return `${formatMoney(client.planAmount)}${client.planWeekday ? ` · по ${WEEKDAY_NAMES[client.planWeekday]}` : ' · еженедельно'}`;
    }
    const first = `${formatMoney(client.planAmount)}${client.planDay ? ` · до ${client.planDay} числа` : ' · ежемесячно'}`;
    if (client.planAmount2) {
      const second = `${formatMoney(client.planAmount2)}${client.planDay2 ? ` · до ${client.planDay2} числа` : ''}`;
      return `Аванс: ${first} + Остаток: ${second}`;
    }
    return first;
  }
  return `${formatMoney(client.planAmount)}${client.planDate ? ` · до ${formatDateShort(client.planDate)}` : ''}`;
}

function renderClientsTable() {
  const el = document.getElementById('clientsTable');
  if (!state.clients.length) {
    el.innerHTML = emptyStateHTML('Пока нет клиентов', 'Добавьте первого клиента, чтобы начать вести учёт', '+ Добавить клиента', 'empty-add-client');
    return;
  }
  const rows = state.clients
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name, 'ru'))
    .map(client => {
      const payments = state.payments.filter(p => p.clientId === client.id);
      const total = payments.filter(p => deriveStatus(p) === 'paid').reduce((s, p) => s + (Number(p.amount) || 0), 0);
      const openCount = payments.filter(p => deriveStatus(p) !== 'paid').length;
      const color = avatarColor(client.id);
      const planLine = clientPlanLineText(client);
      const subLine = planLine || client.tasksDesc || '';
      const sparkline = clientSparklineSVG(client);
      return `
        <div class="ctRow" data-client-id="${client.id}">
          <div class="ctRow__left">
            <div class="row__avatar" style="background:${color.bg}; color:${color.fg};">${initials(client.name)}</div>
            <div>
              <div class="row__title">${escapeHTML(client.name)}</div>
              ${subLine ? `<div class="row__sub">${escapeHTML(subLine)}</div>` : ''}
            </div>
            ${client.type === 'recurring' ? '<span class="badge badge--violet">Постоянный</span>' : '<span class="badge badge--violet" style="background:#FFE8DE;color:#FF7A50;">Разовый</span>'}
            ${client.contract && client.contract.enabled
              ? `<span class="badge badge--contract">Договор · ${client.contract.payerType === 'company' ? '6%' : '4%'}</span>`
              : '<span class="badge badge--nocontract">Без договора</span>'}
          </div>
          <div class="ctRow__stats">
            <div>
              <div class="ctRow__stat-label">Получено всего</div>
              <div class="ctRow__stat-value">${formatMoney(total)}</div>
            </div>
            <div>
              <div class="ctRow__stat-label">Открытых записей</div>
              <div class="ctRow__stat-value">${openCount}</div>
            </div>
            ${sparkline ? `
            <div class="ctRow__sparkline">
              <span class="ctRow__sparkline-label">6 мес.</span>
              ${sparkline}
            </div>` : ''}
          </div>
          <div class="row__actions">
            <button class="iconbtn" title="Добавить задачу" data-action="add-payment-for" data-id="${client.id}">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>
            </button>
            <button class="iconbtn" title="Редактировать" data-action="edit-client" data-id="${client.id}">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M4 20l.8-3.6L16 5.2a1.6 1.6 0 0 1 2.3 0l.5.5a1.6 1.6 0 0 1 0 2.3L7.6 19.2 4 20Z" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg>
            </button>
            <button class="iconbtn iconbtn--danger" title="Удалить клиента" data-action="delete-client" data-id="${client.id}">
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none"><path d="M5 7h14M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2m-9 0 1 13a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2l1-13" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </button>
          </div>
        </div>
      `;
    }).join('');
  el.innerHTML = rows;
}

function escapeHTML(s) {
  return String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

// ---------- Рендер: карточка клиента (детали) ----------

let detailClientId = null;
const clientDetailModal = document.getElementById('clientDetailModal');

function openClientDetail(clientId) {
  const c = getClient(clientId);
  if (!c) return;
  detailClientId = clientId;
  document.getElementById('detailClientName').textContent = c.name;

  const typeBadge = c.type === 'recurring'
    ? '<span class="badge badge--violet">Постоянный</span>'
    : '<span class="badge badge--violet" style="background:#FFE8DE;color:#FF7A50;">Разовый</span>';
  const contractBadge = (c.contract && c.contract.enabled)
    ? `<span class="badge badge--contract">Договор · ${c.contract.payerType === 'company' ? '6%' : '4%'}</span>`
    : '<span class="badge badge--nocontract">Без договора</span>';
  document.getElementById('detailClientMeta').innerHTML = typeBadge + contractBadge;

  const planEl = document.getElementById('detailClientPlan');
  const planText = clientPlanLineText(c);
  planEl.hidden = !planText;
  planEl.textContent = planText ? `По договорённости: ${planText}` : '';

  const tasksEl = document.getElementById('detailClientTasks');
  tasksEl.hidden = !c.tasksDesc;
  tasksEl.textContent = c.tasksDesc || '';

  renderDetailPayments();
  clientDetailModal.classList.add('is-open');
}

function renderDetailPayments() {
  if (!detailClientId) return;
  const payments = state.payments.filter(p => p.clientId === detailClientId).sort(sortByRelevance);
  const el = document.getElementById('detailPayments');
  el.innerHTML = payments.length
    ? payments.map(p => paymentRowHTML(p, { compact: true })).join('')
    : '<div class="empty"><div class="empty__title">Пока нет задач</div><div class="empty__sub">Добавьте первую запись о платеже для этого клиента</div></div>';
}

// ---------- Рендер: отчёты ----------

function firstDayOfMonth(d = new Date()) { return new Date(d.getFullYear(), d.getMonth(), 1); }
function lastDayOfMonth(d = new Date()) { return new Date(d.getFullYear(), d.getMonth() + 1, 0); }

function setReportPreset(preset) {
  const now = new Date();
  let from, to;
  if (preset === 'month') {
    from = firstDayOfMonth(now); to = lastDayOfMonth(now);
  } else if (preset === 'quarter') {
    const q = Math.floor(now.getMonth() / 3);
    from = new Date(now.getFullYear(), q * 3, 1);
    to = new Date(now.getFullYear(), q * 3 + 3, 0);
  } else if (preset === 'year') {
    from = new Date(now.getFullYear(), 0, 1);
    to = new Date(now.getFullYear(), 11, 31);
  } else {
    const dates = state.payments.map(p => p.factDate).filter(Boolean).sort();
    from = dates.length ? new Date(dates[0] + 'T00:00:00') : firstDayOfMonth(now);
    to = now;
  }
  document.getElementById('reportFrom').value = toISO(from);
  document.getElementById('reportTo').value = toISO(to);
  renderReports();
}

function renderReports() {
  const fromEl = document.getElementById('reportFrom');
  const toEl = document.getElementById('reportTo');
  if (!fromEl.value || !toEl.value) return;
  const from = fromEl.value, to = toEl.value;

  const payments = state.payments.filter(p => p.factDate && p.factDate >= from && p.factDate <= to);

  let grossAll = 0, taxAll = 0;
  const byClient = new Map();
  for (const p of payments) {
    const c = getClient(p.clientId);
    if (!c) continue;
    const amount = Number(p.amount) || 0;
    const rate = clientTaxRatePercent(c);
    const tax = amount * rate / 100;
    grossAll += amount; taxAll += tax;
    const agg = byClient.get(c.id) || { name: c.name, type: c.type, gross: 0, tax: 0 };
    agg.gross += amount; agg.tax += tax;
    byClient.set(c.id, agg);
  }
  const netAll = grossAll - taxAll;

  document.getElementById('reportStats').innerHTML = `
    <div class="tile tile--dark">
      <div class="tile__label">Доход за период</div>
      <div class="tile__value">${formatMoney(grossAll)}</div>
    </div>
    <div class="tile">
      <div class="tile__label" style="color:var(--muted)">Налог НПД</div>
      <div class="tile__value">${formatMoney(taxAll)}</div>
    </div>
    <div class="tile">
      <div class="tile__label" style="color:var(--muted)">На руки</div>
      <div class="tile__value">${formatMoney(netAll)}</div>
    </div>
  `;

  const rows = Array.from(byClient.values()).sort((a, b) => b.gross - a.gross);
  const tableEl = document.getElementById('reportTable');
  tableEl.innerHTML = rows.length
    ? rows.map(r => `
      <div class="ctRow">
        <div class="ctRow__left">
          <div>
            <div class="row__title">${escapeHTML(r.name)}</div>
            <div class="row__sub">${r.type === 'recurring' ? 'Постоянный' : 'Разовый'}</div>
          </div>
        </div>
        <div class="ctRow__stats">
          <div><div class="ctRow__stat-label">Доход</div><div class="ctRow__stat-value">${formatMoney(r.gross)}</div></div>
          <div><div class="ctRow__stat-label">Налог</div><div class="ctRow__stat-value">${formatMoney(r.tax)}</div></div>
          <div><div class="ctRow__stat-label">На руки</div><div class="ctRow__stat-value">${formatMoney(r.gross - r.tax)}</div></div>
        </div>
      </div>
    `).join('')
    : '<div class="empty"><div class="empty__title">Нет данных за этот период</div><div class="empty__sub">Попробуйте выбрать другой период или отметьте платежи как оплаченные</div></div>';
}

// ---------- Рендер: всё вместе ----------

function renderAll() {
  renderFirstRun();
  renderDemoBanner();
  renderStats();
  renderMonthProgress();
  renderTaxForecast();
  renderPaymentsCalendar();
  renderClientsTable();
  fillClientSelect();
  renderReports();
  if (clientDetailModal.classList.contains('is-open') && detailClientId) {
    if (getClient(detailClientId)) openClientDetail(detailClientId);
    else clientDetailModal.classList.remove('is-open');
  }
}

// ---------- Навигация по вкладкам ----------

document.querySelectorAll('.navlink').forEach(btn => {
  btn.addEventListener('click', () => {
    document.querySelectorAll('.navlink').forEach(b => b.classList.remove('is-active'));
    btn.classList.add('is-active');
    const view = btn.dataset.view;
    document.querySelectorAll('.view').forEach(v => v.classList.remove('is-active'));
    document.getElementById(`view-${view}`).classList.add('is-active');
  });
});

// ---------- Модалка: клиент ----------

const clientModal = document.getElementById('clientModal');
const clientForm = document.getElementById('clientForm');

function setClientTypeUI(type) {
  document.getElementById('clientType').value = type;
  document.querySelectorAll('#clientForm [data-type]').forEach(o => {
    o.classList.toggle('is-active', o.dataset.type === type);
  });
  document.getElementById('frequencyWrap').hidden = type !== 'recurring';
  document.getElementById('planDateWrap').hidden = type !== 'oneoff';
  if (type !== 'recurring') {
    setFrequencyUI('monthly');
    setSplitPayUI(false);
  } else {
    document.getElementById('planDayWrap').hidden = false;
  }
}

function setFrequencyUI(freq) {
  document.getElementById('clientFrequency').value = freq;
  document.querySelectorAll('#clientForm [data-freq]').forEach(o => {
    o.classList.toggle('is-active', o.dataset.freq === freq);
  });
  const isWeekly = freq === 'weekly';
  document.getElementById('clientPlanDay').hidden = isWeekly;
  document.getElementById('clientPlanWeekday').hidden = !isWeekly;
  document.getElementById('planDayWrap').hidden = document.getElementById('clientType').value !== 'recurring';
  document.getElementById('splitPayWrap').hidden = document.getElementById('clientType').value !== 'recurring' || isWeekly;
  if (isWeekly) setSplitPayUI(false);
  updatePlanDayLabel();
}

function setSplitPayUI(enabled) {
  document.getElementById('clientSplitPay').checked = enabled;
  document.getElementById('splitPayFields').hidden = !enabled;
  updatePlanDayLabel();
  if (!enabled) {
    document.getElementById('clientPlanAmount2').value = '';
    document.getElementById('clientPlanDay2').value = '';
  }
}

function updatePlanDayLabel() {
  const isWeekly = document.getElementById('clientFrequency').value === 'weekly';
  const splitPay = document.getElementById('clientSplitPay').checked;
  document.getElementById('planAmountLabel').textContent = splitPay ? 'Аванс, ₽' : 'Плановая сумма, ₽';
  document.getElementById('planDayLabel').textContent = isWeekly ? 'День недели' : (splitPay ? 'День аванса' : 'День платежа');
}
document.getElementById('clientSplitPay').addEventListener('change', e => setSplitPayUI(e.target.checked));
document.querySelectorAll('#clientForm [data-freq]').forEach(opt => {
  opt.addEventListener('click', () => setFrequencyUI(opt.dataset.freq));
});

function setClientContractUI(enabled) {
  document.getElementById('clientContract').value = enabled ? '1' : '0';
  document.querySelectorAll('#clientForm [data-contract]').forEach(o => {
    o.classList.toggle('is-active', (o.dataset.contract === '1') === enabled);
  });
  document.getElementById('payerTypeWrap').hidden = !enabled;
}

function setPayerTypeUI(type) {
  document.getElementById('clientPayerType').value = type;
  document.querySelectorAll('#clientForm [data-payer]').forEach(o => {
    o.classList.toggle('is-active', o.dataset.payer === type);
  });
}

document.querySelectorAll('#clientForm [data-type]').forEach(opt => {
  opt.addEventListener('click', () => setClientTypeUI(opt.dataset.type));
});
document.querySelectorAll('#clientForm [data-contract]').forEach(opt => {
  opt.addEventListener('click', () => setClientContractUI(opt.dataset.contract === '1'));
});
document.querySelectorAll('#clientForm [data-payer]').forEach(opt => {
  opt.addEventListener('click', () => setPayerTypeUI(opt.dataset.payer));
});

function openClientModal(editId) {
  clientForm.reset();
  document.getElementById('clientId').value = editId || '';
  if (editId) {
    const c = getClient(editId);
    document.getElementById('clientModalTitle').textContent = 'Редактировать клиента';
    document.getElementById('clientName').value = c.name;
    document.getElementById('clientTasks').value = c.tasksDesc || '';
    document.getElementById('clientPlanAmount').value = c.planAmount ?? '';
    document.getElementById('clientPlanDay').value = c.planDay ?? '';
    document.getElementById('clientPlanWeekday').value = c.planWeekday ?? '1';
    document.getElementById('clientPlanDate').value = c.planDate ?? '';
    document.getElementById('clientPlanAmount2').value = c.planAmount2 ?? '';
    document.getElementById('clientPlanDay2').value = c.planDay2 ?? '';
    setClientTypeUI(c.type);
    setFrequencyUI(c.type === 'recurring' && c.planFrequency === 'weekly' ? 'weekly' : 'monthly');
    setSplitPayUI(c.type === 'recurring' && c.planFrequency !== 'weekly' && (c.planAmount2 != null || c.planDay2 != null));
    setClientContractUI(!!(c.contract && c.contract.enabled));
    setPayerTypeUI(c.contract && c.contract.payerType === 'company' ? 'company' : 'individual');
  } else {
    document.getElementById('clientModalTitle').textContent = 'Новый клиент';
    setClientTypeUI('recurring');
    setFrequencyUI('monthly');
    setSplitPayUI(false);
    setClientContractUI(false);
    setPayerTypeUI('individual');
  }
  clientModal.classList.add('is-open');
  document.getElementById('clientName').focus();
}

clientForm.addEventListener('submit', async e => {
  e.preventDefault();
  const id = document.getElementById('clientId').value;
  const name = document.getElementById('clientName').value.trim();
  const type = document.getElementById('clientType').value;
  const tasksDesc = document.getElementById('clientTasks').value.trim();
  const planAmountRaw = document.getElementById('clientPlanAmount').value;
  const planAmount = planAmountRaw ? Number(planAmountRaw) : null;
  const planFrequency = type === 'recurring' ? document.getElementById('clientFrequency').value : 'monthly';
  const isWeekly = planFrequency === 'weekly';
  const planDay = type === 'recurring' && !isWeekly && document.getElementById('clientPlanDay').value
    ? Number(document.getElementById('clientPlanDay').value) : null;
  const planWeekday = type === 'recurring' && isWeekly && document.getElementById('clientPlanWeekday').value
    ? Number(document.getElementById('clientPlanWeekday').value) : null;
  const planDate = type === 'oneoff' ? (document.getElementById('clientPlanDate').value || null) : null;
  const splitPay = type === 'recurring' && !isWeekly && document.getElementById('clientSplitPay').checked;
  const planAmount2 = splitPay && document.getElementById('clientPlanAmount2').value
    ? Number(document.getElementById('clientPlanAmount2').value) : null;
  const planDay2 = splitPay && document.getElementById('clientPlanDay2').value
    ? Number(document.getElementById('clientPlanDay2').value) : null;
  const contractEnabled = document.getElementById('clientContract').value === '1';
  const payerType = document.getElementById('clientPayerType').value;
  if (!name) return;

  const draft = { name, type, tasksDesc, planAmount, planDay, planFrequency, planWeekday, planDate, planAmount2, planDay2, contract: { enabled: contractEnabled, payerType } };
  const row = clientToRow(draft);

  try {
    let savedClient;
    if (id) {
      const { error } = await sb.from('clients').update(row).eq('id', id);
      if (error) throw error;
      savedClient = getClient(id);
      Object.assign(savedClient, draft);
      await clearFutureAutoPayments(id);
    } else {
      const { data, error } = await sb.from('clients').insert(row).select().single();
      if (error) throw error;
      savedClient = rowToClient(data);
      state.clients.push(savedClient);
    }
    await syncClientSchedule(savedClient);
    closeModals();
    renderAll();
    showToast(id ? 'Клиент обновлён' : 'Клиент добавлен');
  } catch (err) {
    console.error(err);
    showToast('Не удалось сохранить клиента');
  }
});

// ---------- Модалка: платёж ----------

const paymentModal = document.getElementById('paymentModal');
const paymentForm = document.getElementById('paymentForm');

function fillClientSelect(selectedId) {
  const select = document.getElementById('paymentClient');
  const current = selectedId || select.value;
  select.innerHTML = state.clients
    .slice().sort((a, b) => a.name.localeCompare(b.name, 'ru'))
    .map(c => `<option value="${c.id}">${escapeHTML(c.name)}${c.type === 'recurring' ? ' · постоянный' : ' · разовый'}</option>`)
    .join('');
  if (current) select.value = current;
}

function updateTaxPreview() {
  const clientId = document.getElementById('paymentClient').value;
  const amount = Number(document.getElementById('paymentAmount').value) || 0;
  const c = getClient(clientId);
  const rate = clientTaxRatePercent(c);
  const el = document.getElementById('taxPreview');
  if (rate > 0 && amount > 0) {
    el.hidden = false;
    el.textContent = `Налог НПД ${rate}%: ${formatMoney(amount * rate / 100)} · на руки: ${formatMoney(amount - amount * rate / 100)}`;
  } else {
    el.hidden = true;
  }
}
document.getElementById('paymentClient').addEventListener('change', updateTaxPreview);
document.getElementById('paymentAmount').addEventListener('input', updateTaxPreview);

function openPaymentModal({ editId, presetClientId } = {}) {
  if (!state.clients.length) {
    showToast('Сначала добавьте клиента');
    openClientModal();
    return;
  }
  paymentForm.reset();
  fillClientSelect(presetClientId);
  document.getElementById('paymentId').value = editId || '';
  document.getElementById('paymentPlanDate').value = todayISO();

  if (editId) {
    const p = state.payments.find(x => x.id === editId);
    document.getElementById('paymentModalTitle').textContent = 'Редактировать запись';
    document.getElementById('paymentClient').value = p.clientId;
    document.getElementById('paymentTask').value = p.task;
    document.getElementById('paymentAmount').value = p.amount;
    document.getElementById('paymentPlanDate').value = p.planDate;
    document.getElementById('paymentFactDate').value = p.factDate || '';
  } else {
    document.getElementById('paymentModalTitle').textContent = 'Новая запись';
  }
  updateTaxPreview();
  paymentModal.classList.add('is-open');
  document.getElementById('paymentTask').focus();
}

paymentForm.addEventListener('submit', async e => {
  e.preventDefault();
  const id = document.getElementById('paymentId').value;
  const clientId = document.getElementById('paymentClient').value;
  const task = document.getElementById('paymentTask').value.trim();
  const amount = Number(document.getElementById('paymentAmount').value) || 0;
  const planDate = document.getElementById('paymentPlanDate').value;
  const factDate = document.getElementById('paymentFactDate').value || null;
  if (!clientId || !task || !planDate) return;

  const draft = { clientId, task, amount, planDate, factDate };
  const row = paymentToRow(draft);

  try {
    if (id) {
      const { error } = await sb.from('payments').update(row).eq('id', id);
      if (error) throw error;
      Object.assign(state.payments.find(x => x.id === id), draft);
    } else {
      const { data, error } = await sb.from('payments').insert(row).select().single();
      if (error) throw error;
      state.payments.push(rowToPayment(data));
    }
    closeModals();
    renderAll();
    showToast(id ? 'Запись обновлена' : 'Запись добавлена');
  } catch (err) {
    console.error(err);
    showToast('Не удалось сохранить запись');
  }
});

// ---------- Общие действия модалок ----------

function closeModals() {
  document.querySelectorAll('.modal').forEach(m => m.classList.remove('is-open'));
}

document.querySelectorAll('[data-close]').forEach(el => el.addEventListener('click', closeModals));
document.querySelectorAll('.modal').forEach(m => {
  m.addEventListener('click', e => { if (e.target === m) closeModals(); });
});
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeModals(); });

// ---------- Делегирование кликов по спискам ----------

document.addEventListener('click', async e => {
  const btn = e.target.closest('[data-action]');
  if (!btn) return;
  const action = btn.dataset.action;
  const id = btn.dataset.id;

  if (action === 'mark-paid') {
    try {
      const rect = btn.getBoundingClientRect();
      const factDate = todayISO();
      const { error } = await sb.from('payments').update({ fact_date: factDate }).eq('id', id);
      if (error) throw error;
      state.payments.find(x => x.id === id).factDate = factDate;
      celebrateAt(rect.left + rect.width / 2, rect.top + rect.height / 2);
      renderAll();
      showToast('Отмечено как оплачено');
    } catch (err) {
      console.error(err);
      showToast('Не удалось обновить запись');
    }
  } else if (action === 'edit-payment') {
    openPaymentModal({ editId: id });
  } else if (action === 'delete-payment') {
    if (confirm('Удалить эту запись?')) {
      try {
        const { error } = await sb.from('payments').delete().eq('id', id);
        if (error) throw error;
        state.payments = state.payments.filter(p => p.id !== id);
        renderAll();
        showToast('Запись удалена');
      } catch (err) {
        console.error(err);
        showToast('Не удалось удалить запись');
      }
    }
  } else if (action === 'edit-client') {
    closeModals();
    openClientModal(id);
  } else if (action === 'delete-client') {
    deleteClientWithConfirm(id);
  } else if (action === 'add-payment-for') {
    openPaymentModal({ presetClientId: id });
  } else if (action === 'empty-add-client') {
    openClientModal();
  } else if (action === 'empty-add-payment') {
    openPaymentModal();
  } else if (action === 'open-day') {
    openDayDetail(btn.dataset.date);
  } else if (action === 'try-demo') {
    btn.disabled = true;
    try {
      await createDemoData();
      showToast('Добавлен пример');
    } catch (err) {
      console.error(err);
      showToast('Не удалось добавить пример');
    } finally {
      // Перерисовываем в любом случае: даже если часть шагов не прошла,
      // экран должен показывать то, что реально лежит в базе
      renderAll();
      btn.disabled = false;
    }
  } else if (action === 'remove-demo') {
    btn.disabled = true;
    try {
      await removeDemoData();
      showToast('Пример убран');
    } catch (err) {
      console.error(err);
      showToast('Не удалось убрать пример');
    } finally {
      renderAll();
      btn.disabled = false;
    }
  } else if (action === 'calendar-prev') {
    calendarMonthOffset -= 1;
    renderPaymentsCalendar();
  } else if (action === 'calendar-next') {
    calendarMonthOffset += 1;
    renderPaymentsCalendar();
  } else if (action === 'calendar-today') {
    calendarMonthOffset = 0;
    renderPaymentsCalendar();
  }
});

async function deleteClientWithConfirm(id) {
  const hasPayments = state.payments.some(p => p.clientId === id);
  const msg = hasPayments
    ? 'У этого клиента есть записи о платежах. Удалить клиента и все его записи?'
    : 'Удалить этого клиента?';
  if (confirm(msg)) {
    try {
      const { error } = await sb.from('clients').delete().eq('id', id);
      if (error) throw error;
      state.clients = state.clients.filter(c => c.id !== id);
      state.payments = state.payments.filter(p => p.clientId !== id);
      closeModals();
      renderAll();
      showToast('Клиент удалён');
    } catch (err) {
      console.error(err);
      showToast('Не удалось удалить клиента');
    }
  }
}

document.getElementById('btnNewPaymentTop').addEventListener('click', () => openPaymentModal());
document.getElementById('btnNewClientTop').addEventListener('click', () => openClientModal());

// ---------- Карточка клиента: открытие по клику на строку ----------

document.getElementById('clientsTable').addEventListener('click', e => {
  if (e.target.closest('[data-action]')) return;
  const row = e.target.closest('.ctRow');
  if (row) openClientDetail(row.dataset.clientId);
});

document.getElementById('btnDetailAddPayment').addEventListener('click', () => {
  openPaymentModal({ presetClientId: detailClientId });
});
document.getElementById('btnDetailEditClient').addEventListener('click', () => {
  closeModals();
  openClientModal(detailClientId);
});
document.getElementById('btnDetailDeleteClient').addEventListener('click', () => {
  deleteClientWithConfirm(detailClientId);
});

// ---------- Отчёты: пресеты и даты ----------

document.querySelectorAll('[data-preset]').forEach(btn => {
  btn.addEventListener('click', () => setReportPreset(btn.dataset.preset));
});
document.getElementById('reportFrom').addEventListener('change', renderReports);
document.getElementById('reportTo').addEventListener('change', renderReports);

// ---------- Настройки: экспорт / импорт / сброс ----------

document.getElementById('btnExport').addEventListener('click', () => {
  const blob = new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `freelab-backup-${todayISO()}.json`;
  a.click();
  URL.revokeObjectURL(url);
});

const importFile = document.getElementById('importFile');
document.getElementById('btnImport').addEventListener('click', () => importFile.click());
importFile.addEventListener('change', () => {
  const file = importFile.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = async () => {
    try {
      const parsed = JSON.parse(reader.result);
      if (!Array.isArray(parsed.clients) || !Array.isArray(parsed.payments)) throw new Error('bad shape');
      if (!confirm('Импорт заменит все текущие данные в облаке резервной копией из файла. Продолжить?')) return;

      const clients = parsed.clients.map(normalizeClient);
      const payments = parsed.payments;

      // Удаляем всё текущее (платежи удалятся каскадом вместе с клиентами)
      const { data: existing, error: exErr } = await sb.from('clients').select('id');
      if (exErr) throw exErr;
      if (existing && existing.length) {
        const { error: delErr } = await sb.from('clients').delete().in('id', existing.map(r => r.id));
        if (delErr) throw delErr;
      }

      // Вставляем клиентов, запоминаем соответствие старых id новым
      const idMap = new Map();
      for (const c of clients) {
        const { data, error } = await sb.from('clients').insert(clientToRow(c)).select().single();
        if (error) throw error;
        idMap.set(c.id, data.id);
      }
      for (const p of payments) {
        const newClientId = idMap.get(p.clientId);
        if (!newClientId) continue;
        const row = paymentToRow({ ...p, clientId: newClientId });
        const { error } = await sb.from('payments').insert(row);
        if (error) throw error;
      }

      await fetchState();
      showToast('Данные загружены');
    } catch (err) {
      console.error(err);
      alert('Не удалось прочитать файл или сохранить данные в облако. Убедитесь, что это резервная копия из Фрилаб.');
    }
  };
  reader.readAsText(file);
  importFile.value = '';
});

document.getElementById('btnReset').addEventListener('click', async () => {
  if (confirm('Точно удалить всех клиентов и все платежи? Это действие необратимо.')) {
    try {
      const { data: existing, error: exErr } = await sb.from('clients').select('id');
      if (exErr) throw exErr;
      if (existing && existing.length) {
        const { error: delErr } = await sb.from('clients').delete().in('id', existing.map(r => r.id));
        if (delErr) throw delErr;
      }
      state = { clients: [], payments: [] };
      renderAll();
      showToast('Все данные удалены');
    } catch (err) {
      console.error(err);
      showToast('Не удалось удалить данные');
    }
  }
});

// ---------- Toast ----------

let toastTimer = null;
function showToast(msg) {
  const el = document.getElementById('toast');
  el.textContent = msg;
  el.classList.add('is-visible');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => el.classList.remove('is-visible'), 2200);
}

// ---------- Инициализация: приветствие ----------

function initGreeting() {
  const hour = new Date().getHours();
  const greet = hour < 6 ? 'Доброй ночи' : hour < 12 ? 'Доброе утро' : hour < 18 ? 'Добрый день' : 'Добрый вечер';
  document.getElementById('greeting').textContent = `${greet}, Наталия 👋`;
  document.getElementById('todayLabel').textContent = `${todayLabel()} — вот как идут дела с клиентами`;
}

// ---------- Аутентификация (Supabase Auth) ----------

const authScreenEl = document.getElementById('authScreen');
const appEl = document.getElementById('app');
const authForm = document.getElementById('authForm');
const authEmailInput = document.getElementById('authEmail');
const authPasswordInput = document.getElementById('authPassword');
const authErrorEl = document.getElementById('authError');
const authSubmitBtn = document.getElementById('authSubmitBtn');
const authToggleBtn = document.getElementById('authToggleMode');
const authForgotLink = document.getElementById('authForgotLink');
const authPasswordField = document.getElementById('authPasswordField');
const authPasswordToggle = document.getElementById('authPasswordToggle');
const btnLogout = document.getElementById('btnLogout');

const recoveryForm = document.getElementById('recoveryForm');
const recoveryPasswordInput = document.getElementById('recoveryPassword');
const recoveryPasswordToggle = document.getElementById('recoveryPasswordToggle');
const recoveryErrorEl = document.getElementById('recoveryError');
const recoverySubmitBtn = document.getElementById('recoverySubmitBtn');

function setupPasswordToggle(input, btn) {
  btn.addEventListener('click', () => {
    const show = input.type === 'password';
    input.type = show ? 'text' : 'password';
    btn.classList.toggle('is-active', show);
  });
}
setupPasswordToggle(authPasswordInput, authPasswordToggle);
setupPasswordToggle(recoveryPasswordInput, recoveryPasswordToggle);

function setNotice(el, text, kind) {
  el.hidden = false;
  el.className = kind === 'ok' ? 'authNotice' : 'authError';
  el.textContent = text;
}

let authMode = 'signin'; // 'signin' | 'signup' | 'forgot'

function setAuthMode(mode) {
  authMode = mode;
  authErrorEl.hidden = true;
  authPasswordField.hidden = mode === 'forgot';
  authPasswordInput.required = mode !== 'forgot';
  authToggleBtn.hidden = mode === 'forgot';
  authForgotLink.hidden = mode === 'signup';
  if (mode === 'signup') {
    authSubmitBtn.textContent = 'Зарегистрироваться';
    authToggleBtn.textContent = 'Уже есть аккаунт? Войти';
  } else if (mode === 'forgot') {
    authSubmitBtn.textContent = 'Отправить ссылку для сброса';
    authForgotLink.textContent = 'Назад ко входу';
  } else {
    authSubmitBtn.textContent = 'Войти';
    authToggleBtn.textContent = 'Нет аккаунта? Зарегистрироваться';
    authForgotLink.textContent = 'Забыли пароль?';
  }
}

authToggleBtn.addEventListener('click', () => setAuthMode(authMode === 'signin' ? 'signup' : 'signin'));
authForgotLink.addEventListener('click', () => setAuthMode(authMode === 'forgot' ? 'signin' : 'forgot'));

authForm.addEventListener('submit', async e => {
  e.preventDefault();
  const email = authEmailInput.value.trim();
  authErrorEl.hidden = true;
  authSubmitBtn.disabled = true;
  try {
    if (authMode === 'forgot') {
      const { error } = await sb.auth.resetPasswordForEmail(email, {
        redirectTo: window.location.origin + window.location.pathname,
      });
      if (error) throw error;
      setNotice(authErrorEl, 'Если такой e-mail зарегистрирован, на него отправлена ссылка для сброса пароля.', 'ok');
    } else if (authMode === 'signup') {
      const password = authPasswordInput.value;
      const { data, error } = await sb.auth.signUp({ email, password });
      if (error) throw error;
      if (!data.session) {
        setAuthMode('signin');
        setNotice(authErrorEl, 'Проверьте почту и подтвердите e-mail, затем войдите.', 'ok');
      }
    } else {
      const password = authPasswordInput.value;
      const { error } = await sb.auth.signInWithPassword({ email, password });
      if (error) throw error;
    }
  } catch (err) {
    setNotice(authErrorEl, err.message === 'Invalid login credentials'
      ? 'Неверный e-mail или пароль'
      : (err.message || 'Ошибка входа'), 'error');
  } finally {
    authSubmitBtn.disabled = false;
  }
});

recoveryForm.addEventListener('submit', async e => {
  e.preventDefault();
  const password = recoveryPasswordInput.value;
  recoveryErrorEl.hidden = true;
  recoverySubmitBtn.disabled = true;
  try {
    const { error } = await sb.auth.updateUser({ password });
    if (error) throw error;
    recoveryMode = false;
    showToast('Пароль обновлён');
    const { data } = await sb.auth.getSession();
    if (data.session) showApp(data.session); else showAuth();
  } catch (err) {
    setNotice(recoveryErrorEl, err.message || 'Не удалось обновить пароль', 'error');
  } finally {
    recoverySubmitBtn.disabled = false;
  }
});

async function doLogout() {
  await sb.auth.signOut();
}

btnLogout.addEventListener('click', doLogout);
document.getElementById('btnLogoutMobile')?.addEventListener('click', doLogout);

let loadedForUserId = null;

function showApp(session) {
  authScreenEl.hidden = true;
  appEl.hidden = false;
  authForm.hidden = false;
  recoveryForm.hidden = true;
  document.getElementById('sidebarEmail').textContent = session.user.email;
  const settingsEmail = document.getElementById('settingsEmail');
  if (settingsEmail) settingsEmail.textContent = session.user.email;
  initGreeting();
  // Supabase может прислать несколько событий авторизации подряд (вход, обновление токена);
  // данные загружаем один раз на пользователя, а не при каждом таком событии
  if (loadedForUserId !== session.user.id) {
    loadedForUserId = session.user.id;
    renderSkeleton();
    fetchState();
  }
}

function showAuth() {
  appEl.hidden = true;
  authScreenEl.hidden = false;
  authForm.hidden = false;
  recoveryForm.hidden = true;
  authForm.reset();
  setAuthMode('signin');
}

function showRecovery() {
  appEl.hidden = true;
  authScreenEl.hidden = false;
  authForm.hidden = true;
  recoveryForm.hidden = false;
}

let recoveryMode = false;

sb.auth.onAuthStateChange((event, session) => {
  if (event === 'PASSWORD_RECOVERY') {
    recoveryMode = true;
    showRecovery();
    return;
  }
  if (recoveryMode) return;
  if (session) showApp(session);
  else { loadedForUserId = null; showAuth(); }
});

sb.auth.getSession().then(({ data }) => {
  if (recoveryMode) return;
  if (data.session) showApp(data.session);
  else showAuth();
});
